---
title: "WHO Cholesterol Load Data"
author: "Steve Bargelt"
date: "August 31, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
knitr::opts_chunk$set(cache=TRUE)
```

### Load packages

```{r load-packages, message=FALSE}
library(WHO)
```

### Sources and More Information

[World Health Organization (WHO) Global Health Observatory (GHO)](http://www.who.int/gho/en/)

[WHO Cholesterol Data](http://apps.who.int/gho/data/node.main.A883?lang=en)

[WHO Ischaemic Data](https://rho.emro.who.int/rhodata/node.main.A1079?lang=en)

[WHO Cerebrovascular Data](https://rho.emro.who.int/rhodata/node.main.A1073?lang=en)



### Use the WHO API to get the data we want to analyze.
```{r download-data}

CHO_Age_Stand <- get_data("CHOL_03")
CHO_Crude <- get_data("CHOL_04")
#CVD_Cerebrovascular_DALY <- get_data("SA_0000001689")
CVD_Cerebrovascular <- get_data("SA_0000001690")
#CVD_Ischaemic_DALY <- get_data("SA_0000001425")
CVD_Ischaemic <- get_data("SA_0000001444")

```

### Save Data Files

```{r save-data-files}

#Change the working directory
setwd("~/code-Stats/WHO")
save(CHO_Age_Stand, file="CHO_Age_Stand.RData")
save(CHO_Crude, file="CHO_Crude.RData")
#save(CVD_Cerebrovascular_DALY, file="CVD_Cerebrovascular_DALY.RData")
save(CVD_Cerebrovascular, file="CVD_Cerebrovascular.RData")
#save(CVD_Ischaemic_DALY, file="CVD_Ischaemic_DALY.RData")
save(CVD_Ischaemic, file="CVD_Ischaemic.RData")

```